name: duwitku
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  camera: ^0.11.3
  collection: ^1.19.1
  csv: ^6.0.0
  dio: ^5.9.0
  fl_chart: ^1.1.1
  flex_color_scheme: ^8.3.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_multi_formatter: ^2.13.10
  flutter_riverpod: ^3.0.3
  flutter_slidable: ^4.0.3
  go_router: ^17.0.0
  google_nav_bar: ^5.0.7
  google_sign_in: ^7.2.0
  grouped_list: ^6.0.0
  http: ^1.6.0
  image: ^4.5.4
  image_cropper: ^11.0.0
  image_picker: ^1.2.1
  intl: ^0.20.2
  material_symbols_icons: ^4.2874.0
  path: ^1.9.1
  path_provider: ^2.1.5
  pdf: ^3.11.3
  permission_handler: ^12.0.1
  riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  share_plus: ^12.0.1
  sign_in_button: ^4.0.1
  skeletonizer: ^2.1.0+1
  supabase_flutter: ^2.10.3
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.9.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env
